# Generated by Django 5.2.3 on 2025-07-04 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_isbn_isbn_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbn',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isbns', to='books.book'),
        ),
    ]
