# Generated by Django 5.2.3 on 2025-07-05 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_isbn_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10, message='Title must be at least 10 characters long'), django.core.validators.MaxLengthValidator(50, message='Title must not exceed 50 characters')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='Category name must be at least 2 characters long.')]),
        ),
    ]
